# Generated by Django 4.2.3 on 2023-09-20 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cook', '0002_recipe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='preparation_time',
        ),
    ]
